version: '3'
services:
    client:
        image: darkchess-client:latest
        ports:
            - 5005:5005
        command: "/bin/bash -c 'source venv/bin/activate && gunicorn -w 1 --worker-class eventlet -b 0.0.0.0:5005 --access-logfile - --error-logfile - dark_chess_frontend:app'"