version: '3'
services:
    nginx:
        image: nginx:stable
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - api
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./data/db:/var/lib/postgresql/data
        expose:
            - "5432"
    api:
        image: darkchess-api:latest
        environment:
            DB_HOST: 'postgres:5432'
            DB_NAME: ${DB_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USERNAME: ${DB_USER}
        links:
            - postgres
        ports:
            - 5000:5000
        command: "/bin/bash -c 'source venv/bin/activate && flask db upgrade && gunicorn -w 1 -b 0.0.0.0:5000 --access-logfile - --error-logfile - dark_chess_backend:app'"