"""empty message

Revision ID: 992b2e2304e9
Revises: 5c8cbe8bc90c
Create Date: 2020-09-30 20:43:54.674677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992b2e2304e9'
down_revision = '5c8cbe8bc90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationship',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('FRIEND', 'FRIEND_REQUEST', 'BLOCKED', name='userrelationshiptype'), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'related_user_id', 'relationship_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relationship')
    # ### end Alembic commands ###
