"""Models for invite-only period.

Revision ID: 5c8cbe8bc90c
Revises: bd5c8d5b7291
Create Date: 2020-09-16 14:52:49.672798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8cbe8bc90c'
down_revision = 'bd5c8d5b7291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_code',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_beta_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beta_code_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['beta_code_id'], ['beta_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_beta_code')
    op.drop_table('beta_code')
    # ### end Alembic commands ###
